version: "3.8"

services:

  database:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - config/.env.prod
    restart: always

  mysite:
    build:
      context: .
      dockerfile: mysite.dockerfile
    command: bash -c "python /app/manage.py migrate && python manage.py ensure_adminuser && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    env_file:
      - config/.env.prod
    depends_on:
      - database
    restart: always